apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-service
  namespace: piggymetricss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-service
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      initContainers:
      - name: wait-for-config
        image: busybox:1.35
        command: ['sh', '-c', 'until wget -qO- http://config-service:8888/actuator/health | grep -q "UP"; do echo waiting for config to be healthy; sleep 5; done']
      containers:
      - name: registry-service
        image: asha515/piggymetrics-registry:latest
        ports:
        - containerPort: 8761
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: CONFIG_SERVICE_PASSWORD
        readinessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: piggymetricss
spec:
  selector:
    app: registry-service
  ports:
  - port: 8761
    targetPort: 8761
  type: ClusterIP