apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: piggymetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: sqshq/piggymetrics-registry
        ports:
        - containerPort: 8761
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: CONFIG_SERVICE_PASSWORD
        readinessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: piggymetrics
spec:
  selector:
    app: registry
  ports:
  - port: 8761
    targetPort: 8761
  type: ClusterIP