apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service
  namespace: piggymetricss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-service
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      initContainers:
      - name: wait-for-config
        image: busybox:1.35
        command: ['sh', '-c', 'until nslookup config.piggymetrics.svc.cluster.local; do echo waiting for config; sleep 2; done']
      containers:
      - name: statistics-service
        image: asha515/piggymetrics-statistics-service:latest
        ports:
        - containerPort: 7000
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: CONFIG_SERVICE_PASSWORD
        - name: MONGODB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: MONGODB_PASSWORD
        - name: STATISTICS_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: STATISTICS_SERVICE_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: statistics-service
  namespace: piggymetricss
spec:
  selector:
    app: statistics-service
  ports:
  - port: 7000
    targetPort: 7000
  type: ClusterIP