apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: piggymetricss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      initContainers:
      - name: wait-for-config
        image: busybox:1.35
        command: ['sh', '-c', 'until nslookup config.piggymetrics.svc.cluster.local; do echo waiting for config; sleep 2; done']
      containers:
      - name: notification-service
        image: asha515/piggymetrics-notification-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: CONFIG_SERVICE_PASSWORD
        - name: MONGODB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: MONGODB_PASSWORD
        - name: NOTIFICATION_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: NOTIFICATION_SERVICE_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: piggymetricss
spec:
  selector:
    app: notification-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP