apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: piggymetricss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
      - name: wait-for-config
        image: busybox:1.35
        command: ['sh', '-c', 'until wget -qO- http://config-service:8888/actuator/health | grep -q "UP"; do echo waiting for config to be healthy; sleep 5; done']
      containers:
      - name: gateway
        image: asha515/piggymetrics-gateway:latest
        ports:
        - containerPort: 4000
        env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: piggymetrics-config
              key: CONFIG_SERVICE_PASSWORD
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: piggymetricss
spec:
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 4000
  type: LoadBalancer